name = "pico_bsp"
description = "Board support package for Raspberry Pi Pico"
version = "2.0.0-alpha"
licenses = "BSD-3-Clause"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "raspberrypi", "pico", "rp2040", "bsp"]
website = "https://pico-doc.synack.me/"

[[depends-on]]
hal = "~0.3"
rp2040_hal = "^2.0"

[configuration.values]
rp2040_hal.Flash_Chip = "w25qxx"

[[pins]]
rp2040_hal = { url='https://github.com/JeremyGrosser/rp2040_hal' }
